<script setup>
import { onMounted, nextTick } from 'vue';
import { useRoute } from 'vue-router';

const route = useRoute();

onMounted(async () => {
	await nextTick();
	if (route.hash === '#privacy') {
		const element = document.getElementById('privacy');
		if (element) {
			element.scrollIntoView({ behavior: 'smooth' });
		}
	}
});
</script>

<template>
	<div id="privacy">
		<h2 class="amaranth">Privacy Policy</h2>
		<h3 class="amaranth">Contact Form Submissions</h3>
		<p>
			If you choose to reach out to us using our contact form, we collect your name and email address to respond
			to your specific inquiry. We only use this information to communicate directly with you regarding your
			message. Submitting a contact form will not sign you up for any unsolicited newsletters nor do we use your
			email for marketing purposes, sell or share it with third parties.
		</p>
		<h3 class="amaranth">How We Use Google Analytics</h3>
		<p>
			We use Google Analytics to help understand how visitors engage with our website. This service uses cookies
			to collect standard internet log information and visitor behavior information in an anonymous form. The
			information generated by the cookie about your use of the website (including IP address) is transmitted to
			Google. This information is then used to evaluate visitors&#39; use of the website and to compile
			statistical reports on website activity for us.
		</p>
		<p>
			We do not use Google Analytics to track, collect, or match any personally identifiable information of our
			visitors. If you wish to opt out of Google Analytics tracking on all websites, you can download and install
			the official
			<a
				href="https://support.google.com/analytics/answer/181881"
				title="Google Analytics Opt-out Browser Add-on"
				target="_blank"
				>Google Analytics Opt-out Browser Add-on</a
			>
			You can also learn more about how Google safeguards your data by visiting the
			<a
				href="https://policies.google.com/technologies/partner-sites"
				title="Google Privacy &amp; Terms"
				target="_blank"
				>Google Privacy &amp; Terms page</a
			>.
		</p>
		<p>
			This site is protected by reCAPTCHA and the Google
			<strong>
				<a title="Privacy Policy" target="_blank" href="https://policies.google.com/privacy">Privacy Policy</a>
			</strong>
			and
			<strong>
				<a title="Terms of Service" target="_blank" href="https://policies.google.com/terms"
					>Terms of Service</a
				>
			</strong>
			apply.
		</p>
	</div>
</template>

<style scoped>
#privacy {
	color: #222;
	background-color: rgb(219 221 247 / 80%);
	border-radius: 8px;
	margin: 1.8em auto 0;
	padding: 1em 1.8em;
	/* width: fit-content; */
	width: 95%;
	max-width: 80em;
}

h1,
h2 {
	text-align: center;
}

h3 {
	margin: 1em	0 0.5em;
}
p {
	text-indent: 1.5em;
	margin-bottom: 1em;
}

@media (min-width: 768px) {
	#privacy {
		width: 80%;
	}
}
</style>
